#ifdef PSP2
// Gameplay frame measurements (see vita_perf.h and docs/DEVELOPMENT.md).
// This build removes the software frame limiter;
// presentation still follows the existing vsync preference.
#include <atomic>
#include <ctype.h>
#include <malloc.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <psp2/display.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/kernel/threadmgr.h>
#include <vitaGL.h>
#include "gl_vita.h"
#include "vita.h"
#include "vita_perf.h"
#include "vita_perf_stats.h"
#include "vita_log.h"
#if __has_include("vita_build_id.h")
#include "vita_build_id.h"	// generated by vita/CMakeLists.txt
#endif
#ifndef VITA_BUILD_ID
#define VITA_BUILD_ID "unknown"
#endif

#ifndef VITA_DATA_DIR
#define VITA_DATA_DIR "ux0:data/reLCS/"
#endif

static VitaPerfSettings settings = { -1, 5, true };

const VitaPerfSettings &
VitaPerfGetSettings(void)
{
	return settings;
}

uint64_t
VitaPerfNow(void)
{
	return sceKernelGetProcessTimeWide();
}

// ---- Settings -------------------------------------------------------------------

// The game reads reLCS.ini much later (and rewrites it keeping unknown keys);
// the GL entry points are chosen before that, so read [VitaPerf] directly.
static void
ReadSettings(void)
{
	FILE *f = fopen(VITA_DATA_DIR "reLCS.ini", "r");
	if(f == nullptr)
		return;
	char line[160];
	bool inSection = false;
	while(fgets(line, sizeof(line), f)){
		char *s = line;
		while(isspace((unsigned char)*s)) s++;
		char *end = s + strlen(s);
		while(end > s && isspace((unsigned char)end[-1])) *--end = '\0';
		if(*s == '['){
			inSection = strncasecmp(s, "[VitaPerf]", 10) == 0;
			continue;
		}
		char *eq = strchr(s, '=');
		if(!inSection || eq == nullptr)
			continue;
		*eq = '\0';
		for(char *k = eq; k > s && isspace((unsigned char)k[-1]); ) *--k = '\0';
		int value = atoi(eq + 1);
		// Ignore old FrameLimit=0/30/60 entries: installing this build must
		// actually unlock gameplay, even with a config from an earlier test.
		if(strcasecmp(s, "ReportSeconds") == 0)
			settings.reportSeconds = value < 1 ? 1 : value > 60 ? 60 : value;
		else if(strcasecmp(s, "GLCounters") == 0)
			settings.glCounters = value != 0;
	}
	fclose(f);
#ifdef RELCS_BENCHMARK
	// Draw modes and flat textures live in the counting wrappers (gl_vita.cpp).
	settings.glCounters = true;
#endif
}

// ---- Allocation counters (-Wl,--wrap=malloc,... in vita/CMakeLists.txt) --------

// Every thread; malloc/calloc/realloc/memalign and free, which includes C++ new
// and delete. newlib's internal _malloc_r users (stdio buffers) are not seen.
static std::atomic<uint32_t> allocCalls, allocBytes, freeCalls;
#ifdef RELCS_BENCHMARK
// Benchmark totals: the window counters are reset at each window start.
static std::atomic<uint32_t> totalAllocCalls, totalAllocBytes, totalFreeCalls;
static std::atomic<uint32_t> totalDiskReads, totalDiskBytes, totalDiskUs, totalSyncWaits, totalSyncUs;
#endif

extern "C" {
void *__real_malloc(size_t size);
void *__real_calloc(size_t n, size_t size);
void *__real_realloc(void *p, size_t size);
void *__real_memalign(size_t align, size_t size);
void __real_free(void *p);

static inline void
CountAlloc(size_t size)
{
	allocCalls.fetch_add(1, std::memory_order_relaxed);
	allocBytes.fetch_add((uint32_t)size, std::memory_order_relaxed);
#ifdef RELCS_BENCHMARK
	totalAllocCalls.fetch_add(1, std::memory_order_relaxed);
	totalAllocBytes.fetch_add((uint32_t)size, std::memory_order_relaxed);
#endif
}

void *__wrap_malloc(size_t size) { CountAlloc(size); return __real_malloc(size); }
void *__wrap_calloc(size_t n, size_t size) { CountAlloc(n * size); return __real_calloc(n, size); }
void *__wrap_realloc(void *p, size_t size) { CountAlloc(size); return __real_realloc(p, size); }
void *__wrap_memalign(size_t align, size_t size) { CountAlloc(size); return __real_memalign(align, size); }

void
__wrap_free(void *p)
{
	if(p){
		freeCalls.fetch_add(1, std::memory_order_relaxed);
#ifdef RELCS_BENCHMARK
		totalFreeCalls.fetch_add(1, std::memory_order_relaxed);
#endif
	}
	__real_free(p);
}
}

// ---- Storage, streaming and threads -------------------------------------------

static std::atomic<uint32_t> diskReads, diskBytes, diskUs, diskMaxUs, diskQueueMax;
static std::atomic<uint32_t> syncWaits, syncUs, syncMaxUs;
static int streamRequestedMax;
static uint32_t streamUsedPeak, streamAvailable;

static void
AtomicMax(std::atomic<uint32_t> &value, uint32_t x)
{
	uint32_t old = value.load(std::memory_order_relaxed);
	while(x > old && !value.compare_exchange_weak(old, x, std::memory_order_relaxed))
		;
}

void
VitaPerfDiskRead(uint32_t bytes, uint64_t us)
{
	diskReads.fetch_add(1, std::memory_order_relaxed);
	diskBytes.fetch_add(bytes, std::memory_order_relaxed);
	diskUs.fetch_add((uint32_t)us, std::memory_order_relaxed);
	AtomicMax(diskMaxUs, (uint32_t)us);
#ifdef RELCS_BENCHMARK
	totalDiskReads.fetch_add(1, std::memory_order_relaxed);
	totalDiskBytes.fetch_add(bytes, std::memory_order_relaxed);
	totalDiskUs.fetch_add((uint32_t)us, std::memory_order_relaxed);
#endif
}

void
VitaPerfDiskSync(uint64_t us)
{
	syncWaits.fetch_add(1, std::memory_order_relaxed);
	syncUs.fetch_add((uint32_t)us, std::memory_order_relaxed);
	AtomicMax(syncMaxUs, (uint32_t)us);
#ifdef RELCS_BENCHMARK
	totalSyncWaits.fetch_add(1, std::memory_order_relaxed);
	totalSyncUs.fetch_add((uint32_t)us, std::memory_order_relaxed);
#endif
}

void
VitaPerfDiskQueued(int depth)
{
	if(depth > 0)
		AtomicMax(diskQueueMax, (uint32_t)depth);
}

void
VitaPerfStreaming(int requested, uint32_t memoryUsed, uint32_t memoryAvailable)
{
	if(requested > streamRequestedMax) streamRequestedMax = requested;
	if(memoryUsed > streamUsedPeak) streamUsedPeak = memoryUsed;
	streamAvailable = memoryAvailable;
}

struct ThreadSlot {
	const char *name;
	SceUID thid;
	SceUInt64 baseline;
	std::atomic<bool> ready;
};
#define MAX_THREADS 8
static ThreadSlot threads[MAX_THREADS];
static std::atomic<int> numThreads;

void
VitaPerfRegisterThread(const char *name)
{
	int i = numThreads.fetch_add(1);
	if(i >= MAX_THREADS)
		return;
	threads[i].name = name;
	threads[i].thid = sceKernelGetThreadId();
	threads[i].ready.store(true, std::memory_order_release);
}

static bool
ThreadRunTime(ThreadSlot &t, SceUInt64 *run)
{
	if(!t.ready.load(std::memory_order_acquire))
		return false;
	SceKernelThreadInfo info;
	memset(&info, 0, sizeof(info));
	info.size = sizeof(info);
	if(sceKernelGetThreadInfo(t.thid, &info) < 0)
		return false;
	*run = info.runClocks;
	return true;
}

// ---- Presentation (vitaGL display queue) ------------------------------------------

// vitaGL calls the display callback on its display queue thread just before
// each flip. The callback only stores the flip; the main thread pairs it with
// its swap (VitaFlipMatcher) once it knows whether that was a gameplay frame.
// vcount steps give how long each image stayed on screen.
static VitaFlipMatcher matcher;

struct Flip {
	uint32_t index;
	int vcount;
	uint64_t time;
};
#define FLIP_RING 256
static Flip flips[FLIP_RING];
static std::atomic<uint32_t> flipHead, flipTail, flipsLost;

static void
OnDisplayFlip(void *)
{
	static uint32_t index;
	uint32_t head = flipHead.load(std::memory_order_relaxed);
	if(head - flipTail.load(std::memory_order_acquire) >= FLIP_RING){
		flipsLost.fetch_add(1, std::memory_order_relaxed);
		index++;
		return;
	}
	Flip &f = flips[head % FLIP_RING];
	f.index = index++;
	f.vcount = sceDisplayGetVcount();
	f.time = sceKernelGetProcessTimeWide();
	flipHead.store(head + 1, std::memory_order_release);
}

void
VitaPerfGLReady(void)
{
	vglSetDisplayCallback(OnDisplayFlip);
}

// ---- Report window ----------------------------------------------------------------

static bool firstGameFrameLogged;
static uint64_t lastReport;
static unsigned windowIndex;
#ifdef RELCS_BENCHMARK
static bool periodicReports = true;
static const char *reportScene;	// set while VitaPerfSceneWindowEnd writes
static bool skipSceneFrame;	// the frame that opened a scene window is not measured
#define PERIODIC_REPORTS periodicReports
#else
#define PERIODIC_REPORTS true
#endif

// Idle in progress
static bool inIdle, idleMenu;
static int idleSwaps;
static uint32_t idleFirstSubmit;
static uint64_t idleBegin, swapBegin, swapEnd;
static unsigned swapsTotal, swapsAtIdleEnd;

// Previous gameplay frame, while frames follow each other without a break
static bool havePrevious;
static uint64_t prevSwapEnd, prevIdleBegin, prevIdleEnd, pendingReportUs;
static uint32_t prevGameTime;
static bool prevPaused;

// Current window: consecutive gameplay frames only
static uint64_t windowStart, lastGameEnd;
static unsigned gameFrames;
static VitaSampleSeries intervals, workTimes, latencies;
static uint32_t scratch[VitaSampleSeries::CAPACITY];
static uint64_t workSum, swapSum, waitSum, postSum, reportCost;
static uint32_t swapMax;
static uint64_t gameMsSum, realUsSum;
static unsigned clampedFrames, pausedFrames;
static VitaHoldHistogram holds;
static unsigned flipsGame, unmatchedSeen;
static uint32_t flipsLostSeen;
static unsigned excludedMenu, excludedLoad, excludedNoSwap, outsideSwaps;
// Baselines taken at the window's first frame
static SceKernelSystemInfo cpuBaseline;
static bool cpuBaselineValid;
static uint64_t sampleTime;
static size_t poolMinFree[4];
static unsigned heapMaxUsed;
static const vglMemType pools[4] = { VGL_MEM_RAM, VGL_MEM_VRAM, VGL_MEM_PHYCONT, VGL_MEM_BUDGET };
static const char *poolNames[4] = { "ram", "cdram", "phycont", "budget" };

static void
DrainFlips(void)
{
	uint32_t head = flipHead.load(std::memory_order_acquire);
	uint32_t tail = flipTail.load(std::memory_order_relaxed);
	for(; tail != head; tail++){
		const Flip &f = flips[tail % FLIP_RING];
		if(matcher.Flip(f.index, f.vcount, f.time, &holds, &latencies))
			flipsGame++;
	}
	flipTail.store(tail, std::memory_order_release);
}

static void
SampleMemory(uint64_t now)
{
	if(now - sampleTime < 500000)
		return;
	sampleTime = now;
	for(int i = 0; i < 4; i++){
		size_t free = vglMemFree(pools[i]);
		if(free < poolMinFree[i]) poolMinFree[i] = free;
	}
	// Heap usage is sampled every 0.5 s by VitaRecordPresentedFrame.
	unsigned used = VitaGetPerformanceStats().heapUsed;
	if(used > heapMaxUsed) heapMaxUsed = used;
}

static void
StartWindow(uint64_t now)
{
	windowStart = now;
	gameFrames = 0;
	intervals.Reset();
	workTimes.Reset();
	latencies.Reset();
	workSum = swapSum = waitSum = postSum = reportCost = 0;
	swapMax = 0;
	gameMsSum = realUsSum = 0;
	clampedFrames = pausedFrames = 0;
	holds.Reset();
	flipsGame = 0;
	unmatchedSeen = matcher.Unmatched();
	flipsLostSeen = flipsLost.load(std::memory_order_relaxed);

	memset(&cpuBaseline, 0, sizeof(cpuBaseline));
	cpuBaseline.size = sizeof(cpuBaseline);
	cpuBaselineValid = sceKernelGetSystemInfo(&cpuBaseline) >= 0;
	int n = numThreads.load() < MAX_THREADS ? numThreads.load() : MAX_THREADS;
	for(int i = 0; i < n; i++)
		if(!ThreadRunTime(threads[i], &threads[i].baseline))
			threads[i].baseline = 0;
	allocCalls.store(0, std::memory_order_relaxed);
	allocBytes.store(0, std::memory_order_relaxed);
	freeCalls.store(0, std::memory_order_relaxed);
	diskReads.store(0); diskBytes.store(0); diskUs.store(0); diskMaxUs.store(0); diskQueueMax.store(0);
	syncWaits.store(0); syncUs.store(0); syncMaxUs.store(0);
	streamRequestedMax = 0;
	streamUsedPeak = 0;
	for(int i = 0; i < 4; i++)
		poolMinFree[i] = (size_t)-1;
	heapMaxUsed = 0;
	sampleTime = 0;
	if(PERIODIC_REPORTS)
		SampleMemory(now);
}

static const char *
LimitName(void)
{
	return "uncapped";
}

// A partial window ends at a phase change: its frame statistics stop at the
// last gameplay frame, while CPU, thread, storage and allocation rates run to
// `now` and include the tail (tail_ms) of the frame that ended the window.
static void
WriteReport(uint64_t now, bool partial)
{
	uint64_t start = VitaPerfNow();
	double secs = (lastGameEnd - windowStart) / 1000000.0;
	VitaSampleSummary frame, work, latency;
	intervals.Summarise(&frame, scratch);
	workTimes.Summarise(&work, scratch);
	latencies.Summarise(&latency, scratch);
	unsigned n = intervals.Count();
	const char *sceneKey = "", *sceneId = "";
#ifdef RELCS_BENCHMARK
	if(reportScene){
		sceneKey = " scene=";
		sceneId = reportScene;
	}
#endif

	// Same first line as the stable build, over gameplay frames only
	if(n)
		printf("[VITA] %.1f fps, %.1f ms/frame, swap (GPU wait) %.1f ms/frame\n",
		       1000.0 / frame.meanMs, frame.meanMs, swapSum / 1000.0 / n);
	printf("[PERF] window=%u build=%s phase=game frames=%u intervals=%u secs=%.2f limit=%s partial=%d tail_ms=%.1f%s%s\n",
	       windowIndex++, VITA_BUILD_ID, gameFrames, n, secs, LimitName(), partial, (now - lastGameEnd) / 1000.0,
	       sceneKey, sceneId);
	if(n){
		printf("[PERF] frame_ms mean=%.2f median=%.2f p95=%.2f p99=%.2f min=%.2f max=%.2f over33=%.1f%% over50=%.1f%% dropped=%u\n",
		       frame.meanMs, frame.medianMs, frame.p95Ms, frame.p99Ms, frame.minMs, frame.maxMs,
		       100.0 * frame.over33 / n, 100.0 * frame.over50 / n, intervals.Dropped());
		if(frame.fpsWindows)
			printf("[PERF] fps_1s min=%.1f max=%.1f windows=%u\n", frame.fpsMin, frame.fpsMax, frame.fpsWindows);
		else
			printf("[PERF] fps_1s windows=0\n");
		printf("[PERF] split_ms work=%.2f work_p95=%.2f work_max=%.2f swap=%.2f swap_max=%.2f wait=%.2f post=%.2f report_included=%.2f\n",
		       workSum / 1000.0 / n, work.p95Ms, work.maxMs, swapSum / 1000.0 / n, swapMax / 1000.0,
		       waitSum / 1000.0 / n, postSum / 1000.0 / n, reportCost / 1000.0);
		printf("[PERF] gametime game_per_real=%.4f clamped=%u paused=%u\n",
		       realUsSum ? gameMsSum * 1000.0 / realUsSum : 0.0, clampedFrames, pausedFrames);
	}
	printf("[PERF] present flips=%u held_1/2/3/4+=%u/%u/%u/%u display_fps=%.1f",
	       flipsGame, holds.held[0], holds.held[1], holds.held[2], holds.held[3], holds.DisplayFPS());
	if(latency.count)
		printf(" latency_ms mean=%.2f p95=%.2f max=%.2f", latency.meanMs, latency.p95Ms, latency.maxMs);
	printf(" unmatched=%u lost=%u estimate=pre_flip_callback\n", matcher.Unmatched() - unmatchedSeen, flipsLost.load(std::memory_order_relaxed) - flipsLostSeen);
	printf("[PERF] excluded menu=%u load=%u noswap=%u outside_swaps=%u\n",
	       excludedMenu, excludedLoad, excludedNoSwap, outsideSwaps);
	excludedMenu = excludedLoad = excludedNoSwap = outsideSwaps = 0;

	// CPU load per core and thread run time, over the window's wall time
	double wall = (double)(now - windowStart);
	printf("[PERF] cpu_pct");
	SceKernelSystemInfo cpu;
	memset(&cpu, 0, sizeof(cpu));
	cpu.size = sizeof(cpu);
	bool haveCPU = cpuBaselineValid && wall > 0 && sceKernelGetSystemInfo(&cpu) >= 0;
	for(int i = 0; i < 4; i++){
		if(haveCPU && (cpu.activeCpuMask & cpuBaseline.activeCpuMask & (1U << i)) &&
		   cpu.cpuInfo[i].idleClock >= cpuBaseline.cpuInfo[i].idleClock){
			double load = 100.0 * (1.0 - (cpu.cpuInfo[i].idleClock - cpuBaseline.cpuInfo[i].idleClock) / wall);
			printf(" core%d=%.0f", i, load < 0.0 ? 0.0 : load > 100.0 ? 100.0 : load);
		}else
			printf(" core%d=--", i);
	}
	printf(" threads_ms_per_s");
	int nt = numThreads.load() < MAX_THREADS ? numThreads.load() : MAX_THREADS;
	for(int i = 0; i < nt; i++){
		SceUInt64 run;
		if(wall > 0 && threads[i].baseline && ThreadRunTime(threads[i], &run))
			printf(" %s=%.0f", threads[i].name, (run - threads[i].baseline) * 1000.0 / wall);
	}
	printf("\n");

#ifdef RELCS_BENCHMARK
	if(!periodicReports){
		// Not sampled during the frames of the window: once, now.
		VitaSampleMemoryNow();
		sampleTime = 0;
	}
#endif
	SampleMemory(now);
	printf("[PERF] mem_mib heap_used_max=%.1f/%.0f", heapMaxUsed / 1048576.0,
	       VitaGetPerformanceStats().heapTotal / 1048576.0);
	for(int i = 0; i < 4; i++)
		printf(" %s_free_min=%.1f/%.0f", poolNames[i],
		       poolMinFree[i] == (size_t)-1 ? 0.0 : poolMinFree[i] / 1048576.0, vglMemTotal(pools[i]) / 1048576.0);
	printf(" stream_used_peak=%.1f/%.1f stream_requested_max=%d\n",
	       streamUsedPeak / 1048576.0, streamAvailable / 1048576.0, streamRequestedMax);

	double perSec = wall > 0 ? 1000000.0 / wall : 0.0;
	uint32_t reads = diskReads.load(), waits = syncWaits.load();
	printf("[PERF] disk reads=%u kib=%.0f read_ms=%.1f read_max_ms=%.1f queue_max=%u sync_waits=%u sync_ms=%.1f sync_max_ms=%.1f\n",
	       reads, diskBytes.load() / 1024.0, diskUs.load() / 1000.0, diskMaxUs.load() / 1000.0, diskQueueMax.load(),
	       waits, syncUs.load() / 1000.0, syncMaxUs.load() / 1000.0);
	printf("[PERF] alloc_per_s malloc=%.0f free=%.0f kib=%.0f (all threads)\n",
	       allocCalls.load() * perSec, freeCalls.load() * perSec, allocBytes.load() / 1024.0 * perSec);

	VitaProfReportSections(gameFrames);
	VitaGLProfReport(gameFrames);
	const VitaLogStats log = VitaLogGetStats();
	printf("[PERF] logger async=%d queued_kib=%.1f peak_kib=%.1f dropped_bytes=%u truncated=%u io_errors=%u writer_max_ms=%.2f (cumulative)\n",
	       log.running, log.queued / 1024.0, log.peak / 1024.0, log.dropped, log.truncated, log.errors, log.writeMaxUs / 1000.0);
	VitaFlushLog();

	lastReport = now;
	windowStart = 0;
	// Formatting/enqueueing still delays the next image: keep it in observed
	// FPS. Disk writes now belong to LogWriter, not to this main-thread cost.
	pendingReportUs += VitaPerfNow() - start;
}

// Outside gameplay (front end, loading screens): a heartbeat so the log shows
// the game is alive, without statistics mixing phases.
static void
WriteHeartbeat(uint64_t now, unsigned swaps)
{
	printf("[VITA] %.1f swaps/s outside gameplay (menu or loading)\n",
	       swaps * 1000000.0 / (now - lastReport));
	printf("[PERF] excluded menu=%u load=%u noswap=%u outside_swaps=%u\n",
	       excludedMenu, excludedLoad, excludedNoSwap, outsideSwaps);
	excludedMenu = excludedLoad = excludedNoSwap = outsideSwaps = 0;
	VitaProfReportSections(0);
	VitaGLProfReport(0);
	VitaFlushLog();
	lastReport = now;
}

// ---- Frame hooks ----------------------------------------------------------------

bool
VitaPerfFrameDue(bool limiter, bool vsync, float elapsedMs, int maxFPS)
{
	// No busy wait, sleep deadline or 30 FPS menu setting may gate gameplay.
	(void)limiter; (void)vsync; (void)elapsedMs; (void)maxFPS;
	return true;
}

int
VitaPerfSwapInterval(int interval)
{
	// Retain vsync without dividing the display refresh rate by two.
	return interval ? 1 : 0;
}

void
VitaPerfIdleBegin(bool menu)
{
	// Section and GL times since the last gameplay frame belong to other phases.
	VitaProfDiscardFrame();
	VitaGLProfDiscardFrame();
	if(swapsTotal != swapsAtIdleEnd){
		outsideSwaps += swapsTotal - swapsAtIdleEnd;
		havePrevious = false;
	}
	inIdle = true;
	idleMenu = menu;
	idleSwaps = 0;
	idleFirstSubmit = matcher.Submitted();
	idleBegin = VitaPerfNow();
}

void
VitaPerfSwapBegin(void)
{
	swapBegin = VitaPerfNow();
	matcher.Submit(swapBegin, inIdle ? VitaFlipMatcher::PENDING : VitaFlipMatcher::OTHER);
}

void
VitaPerfSwapEnd(void)
{
	swapEnd = VitaPerfNow();
	swapsTotal++;
	if(inIdle){
		idleSwaps++;
		return;
	}
	DrainFlips();
	// A swap outside Idle (loading screen between two Idles) ends the window.
	if(PERIODIC_REPORTS && windowStart)
		WriteReport(swapEnd, true);
	static unsigned swapsSinceReport;
	swapsSinceReport++;
	if(PERIODIC_REPORTS && swapEnd - lastReport >= settings.reportSeconds * 1000000ULL){
		WriteHeartbeat(swapEnd, swapsSinceReport);
		swapsSinceReport = 0;
	}
}

void
VitaPerfIdleEnd(uint32_t gameTimeMs, bool paused)
{
	uint64_t now = VitaPerfNow();
	bool gameplay = !idleMenu && idleSwaps == 1;
#ifdef RELCS_BENCHMARK
	// the benchmark opened its window mid-frame (possibly after a blocking
	// load): like the benchmark's own records, the window starts after it
	if(skipSceneFrame){
		skipSceneFrame = false;
		gameplay = false;
	}
#endif
	for(uint32_t i = idleFirstSubmit; i != matcher.Submitted(); i++)
		matcher.SetKind(i, gameplay ? VitaFlipMatcher::GAME : VitaFlipMatcher::OTHER);
	inIdle = false;
	swapsAtIdleEnd = swapsTotal;

	if(!gameplay){
		if(idleMenu) excludedMenu++;
		else if(idleSwaps == 0) excludedNoSwap++;
		else excludedLoad++;
		VitaProfDiscardFrame();
		VitaGLProfDiscardFrame();
		havePrevious = false;
		DrainFlips();
		// A phase change ends the gameplay window
		if(PERIODIC_REPORTS && windowStart)
			WriteReport(now, true);
		return;
	}

	VitaProfCommitFrame();
	VitaGLProfCommitFrame();
	if(!firstGameFrameLogged){
		firstGameFrameLogged = true;
		printf("[PERF] first gameplay frame %.2f s after process start\n", now / 1000000.0);
	}
	if(windowStart == 0)
		StartWindow(now);
	gameFrames++;
	lastGameEnd = now;
	if(havePrevious){
		// interval = post (previous frame, after its swap) + wait (limiter and
		// main loop) + work (Idle up to the swap) + swap
		uint64_t interval = swapEnd - prevSwapEnd;
		uint64_t wait = idleBegin - prevIdleEnd;
		reportCost += pendingReportUs;
		intervals.Add((uint32_t)interval);
		uint64_t work = swapBegin - idleBegin;
		workTimes.Add((uint32_t)work);
		workSum += work;
		uint64_t swap = swapEnd - swapBegin;
		swapSum += swap;
		if(swap > swapMax) swapMax = (uint32_t)swap;
		waitSum += wait;
		postSum += prevIdleEnd - prevSwapEnd;
		// CTimer::Update runs first in Idle: compare its progress with real time
		// (report writing included: the game clock counted it too). Steps above
		// 60 ms are clamped by CTimer, slowing the game down.
		uint64_t real = idleBegin - prevIdleBegin;
		if(paused || prevPaused)
			pausedFrames++;
		else{
			gameMsSum += gameTimeMs - prevGameTime;
			realUsSum += real;
			if(real > 60000) clampedFrames++;
		}
	}
	havePrevious = true;
	pendingReportUs = 0;
	prevSwapEnd = swapEnd;
	prevIdleEnd = now;
	prevIdleBegin = idleBegin;
	prevGameTime = gameTimeMs;
	prevPaused = paused;

	DrainFlips();
	if(PERIODIC_REPORTS){
		SampleMemory(now);
		if(now - windowStart >= settings.reportSeconds * 1000000ULL)
			WriteReport(now, false);
	}
}

// ---- Benchmark (vita_bench.cpp) ---------------------------------------------------

#ifdef RELCS_BENCHMARK
void
VitaPerfSetPeriodicReports(bool on)
{
	periodicReports = on;
}

void
VitaPerfSceneWindowBegin(void)
{
	// Frames, rates and baselines restart with StartWindow at the next gameplay
	// frame. Section and GL totals of the kept frames are dropped here without
	// printing; the frame in progress is dropped too (skipSceneFrame).
	windowStart = 0;
	skipSceneFrame = true;
	pendingReportUs = 0;
	excludedMenu = excludedLoad = excludedNoSwap = outsideSwaps = 0;
	VitaProfReportSections(0);
	VitaGLProfReset();
}

void
VitaPerfSceneWindowEnd(const char *scene)
{
	// One token for the log parsers
	char id[48];
	int len = 0;
	for(const char *c = scene ? scene : ""; *c && len < (int)sizeof(id) - 1; c++)
		id[len++] = isspace((unsigned char)*c) || *c == '=' ? '_' : *c;
	if(len == 0)
		id[len++] = '-';
	id[len] = '\0';

	uint64_t now = VitaPerfNow();
	DrainFlips();
	if(windowStart == 0){
		printf("[PERF] scene=%s: no gameplay frame, no window\n", id);
		VitaFlushLog();
		return;
	}
	reportScene = id;
	WriteReport(now, true);
	reportScene = nullptr;
}

int
VitaPerfThreadCount(void)
{
	int n = numThreads.load();
	return n < MAX_THREADS ? n : MAX_THREADS;
}

bool
VitaPerfThreadRunTime(int i, const char **name, uint64_t *runUs)
{
	SceUInt64 run;
	if(i < 0 || i >= VitaPerfThreadCount() || !ThreadRunTime(threads[i], &run))
		return false;
	*name = threads[i].name;
	*runUs = run;
	return true;
}

// 32-bit atomics widened to 64 bits: read far more often than they can wrap.
static uint64_t
Widen(uint64_t &total, uint32_t &last, const std::atomic<uint32_t> &value)
{
	uint32_t now = value.load(std::memory_order_relaxed);
	total += (uint32_t)(now - last);
	last = now;
	return total;
}

void
VitaPerfGetTotals(VitaPerfTotals *out)
{
	static uint64_t total[8];
	static uint32_t last[8];
	out->diskReads = Widen(total[0], last[0], totalDiskReads);
	out->diskBytes = Widen(total[1], last[1], totalDiskBytes);
	out->diskUs = Widen(total[2], last[2], totalDiskUs);
	out->syncWaits = Widen(total[3], last[3], totalSyncWaits);
	out->syncUs = Widen(total[4], last[4], totalSyncUs);
	out->allocCalls = Widen(total[5], last[5], totalAllocCalls);
	out->freeCalls = Widen(total[6], last[6], totalFreeCalls);
	out->allocBytes = Widen(total[7], last[7], totalAllocBytes);
}
#endif

// ---- Startup ----------------------------------------------------------------------

void
VitaPerfInit(void)
{
	ReadSettings();
	VitaPerfRegisterThread("main");
	VitaGLProfSetCounting(settings.glCounters);
	double pairUs = VitaProfCalibrate();
	printf("[PERF] build=%s FrameLimit=%s ReportSeconds=%d GLCounters=%d; profiler section begin+end %.2f us\n",
	       VITA_BUILD_ID, LimitName(), settings.reportSeconds, settings.glCounters, pairUs);
	lastReport = VitaPerfNow();
}
#endif
