// reLCS Benchmark platform layer for the PS Vita (src/extras/benchmark_platform.h).
// Frame data comes from VitaPerf, the section profiler and the GL counting
// wrappers; GPU time from a GXM notification polled on another core; results
// are written with sceIo (absolute paths: sceIo ignores newlib's chdir).
#if defined(PSP2) && defined(RELCS_BENCHMARK)
#include <atomic>
#include <malloc.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <psp2/ctrl.h>
#include <psp2/gxm.h>
#include <psp2/io/fcntl.h>
#include <psp2/io/stat.h>
#include <psp2/kernel/cpu.h>
#include <psp2/kernel/modulemgr.h>
#include <psp2/kernel/processmgr.h>
#include <psp2/kernel/sysmem.h>
#include <psp2/kernel/threadmgr.h>
#include <psp2/power.h>
#include <psp2/rtc.h>
#include <vitaGL.h>
#include "benchmark_platform.h"
#include "gl_vita.h"
#include "vita.h"
#include "vita_log.h"
#include "vita_perf.h"
#if __has_include("vita_build_id.h")
#include "vita_build_id.h"	// generated by vita/CMakeLists.txt
#endif
#ifndef VITA_BUILD_ID
#define VITA_BUILD_ID "unknown"
#endif
#ifndef VITA_DATA_DIR
#define VITA_DATA_DIR "ux0:data/reLCS/"
#endif

#define SCREEN_W 960
#define SCREEN_H 544
#define ERRNO_EEXIST 0x80010011		// SCE_ERROR_ERRNO_EEXIST
#define NOTIFICATION_WORDS 512		// sceGxmGetNotificationRegion() size, 32-bit words
#define BENCH_LOG VITA_DATA_DIR "benchmark/log.txt"

// libvitaGL.a globals that vitaGL.h does not declare (checked with nm/objdump
// on the linked library): gxm.o gxm_context and gc_thread; buffers.o
// query_fence, which reset_queries points at the start of the notification
// region (value 0) and which every sceGxmEndScene (vglSwapBuffers and render
// target switches) passes as its fragment notification after value++.
extern "C" SceGxmContext *gxm_context;
extern "C" SceGxmNotification query_fence;
extern "C" SceUID gc_thread;
extern "C" int _newlib_heap_size_user;	// vita.cpp

static bool initialised;
static bool GLReady(void) { return gxm_context != nullptr; }

// ---- CPU load probe -----------------------------------------------------------

// Hardware runs showed "--" for every core without saying why: log what the
// call returns, and accept both mask layouts (bit i, or the affinity layout
// SCE_KERNEL_CPU_MASK_USER_0 << i).
static bool cpuLoadOk, cpuProbeChecked;
static SceKernelSystemInfo cpuProbe;
static uint64_t cpuProbeTime;
static char cpuNote[64] = "cpu=untested";

static int
ReadSystemInfo(SceKernelSystemInfo *info)
{
	memset(info, 0, sizeof(*info));
	info->size = sizeof(*info);
	return sceKernelGetSystemInfo(info);
}

static bool
CoreValid(const SceKernelSystemInfo &info, int i)
{
	if(info.activeCpuMask & ((1U << i) | (0x10000U << i)))
		return true;
	return info.activeCpuMask == 0 && info.cpuInfo[i].idleClock != 0;
}

static void
LogSystemInfo(const char *when, int rc, const SceKernelSystemInfo &info)
{
	printf("[BENCH] cpu probe %s: rc=0x%08X mask=0x%08X idle_us=%llu/%llu/%llu/%llu\n", when, (unsigned)rc,
	       (unsigned)info.activeCpuMask, (unsigned long long)info.cpuInfo[0].idleClock,
	       (unsigned long long)info.cpuInfo[1].idleClock, (unsigned long long)info.cpuInfo[2].idleClock,
	       (unsigned long long)info.cpuInfo[3].idleClock);
}

static void
ProbeCpuLoad(void)
{
	int rc = ReadSystemInfo(&cpuProbe);
	cpuProbeTime = VitaPerfNow();
	LogSystemInfo("init", rc, cpuProbe);
	cpuLoadOk = false;
	if(rc >= 0)
		for(int i = 0; i < 4; i++)
			if(CoreValid(cpuProbe, i))
				cpuLoadOk = true;
	snprintf(cpuNote, sizeof(cpuNote), "cpu=%s rc=0x%X mask=0x%X", cpuLoadOk ? "probing" : "no",
	         (unsigned)rc, (unsigned)cpuProbe.activeCpuMask);
}

// A few seconds later: idle clocks must have moved on at least one core.
static void
CheckCpuLoad(uint64_t now)
{
	if(cpuProbeChecked || !cpuLoadOk || now - cpuProbeTime < 2000000)
		return;
	cpuProbeChecked = true;
	SceKernelSystemInfo info;
	int rc = ReadSystemInfo(&info);
	LogSystemInfo("recheck", rc, info);
	bool moved = false;
	if(rc >= 0)
		for(int i = 0; i < 4; i++)
			if(CoreValid(info, i) && info.cpuInfo[i].idleClock > cpuProbe.cpuInfo[i].idleClock)
				moved = true;
	cpuLoadOk = moved;
	snprintf(cpuNote, sizeof(cpuNote), "cpu=%s rc=0x%X mask=0x%X", moved ? "ok" : "static",
	         (unsigned)rc, (unsigned)info.activeCpuMask);
	if(!moved)
		printf("[BENCH] cpu load unavailable: idle clocks did not move\n");
}

// ---- GPU fence ------------------------------------------------------------------

enum { FENCE_UNKNOWN, FENCE_PROBING, FENCE_OK, FENCE_FAILED };
static int fenceState;
static const char *fenceWhy = "GL not ready";
static volatile unsigned int *fenceAddress;
static uint32_t probeTarget, lastTarget;
static uint64_t probeStart;

static void
FenceFail(const char *why)
{
	fenceState = FENCE_FAILED;
	fenceWhy = why;
	printf("[BENCH] GPU fence unavailable: %s (address=%p value=%u region=%p)\n", why,
	       (void*)query_fence.address, query_fence.value, GLReady() ? (void*)sceGxmGetNotificationRegion() : nullptr);
}

// Non-blocking, main thread. The fence is trusted once the GPU has written a
// value that the CPU submitted after vitaGL reset it to 0.
static int
CheckFence(void)
{
	if(fenceState == FENCE_OK || fenceState == FENCE_FAILED || !GLReady())
		return fenceState;
	if(query_fence.address == nullptr){
		if(query_fence.value)
			FenceFail("scenes submitted with no notification address");
		return fenceState;
	}
	if(fenceState == FENCE_UNKNOWN){
		volatile unsigned int *region = sceGxmGetNotificationRegion();
		volatile unsigned int *address = query_fence.address;
		if(region == nullptr || address < region || address >= region + NOTIFICATION_WORDS){
			FenceFail("address outside the GXM notification region");
			return fenceState;
		}
		if(query_fence.value == 0)
			return fenceState;	// nothing submitted yet
		fenceAddress = address;
		probeTarget = query_fence.value;
		probeStart = VitaPerfNow();
		fenceState = FENCE_PROBING;
		fenceWhy = "probing";
	}
	uint32_t reached = *fenceAddress;
	if((int32_t)(reached - query_fence.value) > 0)
		FenceFail("GPU value ahead of the submitted value");
	else if((int32_t)(reached - probeTarget) >= 0){
		fenceState = FENCE_OK;
		fenceWhy = "ok";
		printf("[BENCH] GPU fence ok: value %u reached %.1f ms after the probe\n",
		       probeTarget, (VitaPerfNow() - probeStart) / 1000.0);
	}else if(VitaPerfNow() - probeStart > 3000000)
		FenceFail("no progress in 3 s");
	return fenceState;
}

// Caps(): decide now if the GPU has work in flight (a few ms at most).
static int
WaitFence(uint64_t timeoutUs)
{
	uint64_t start = VitaPerfNow();
	while(CheckFence() == FENCE_PROBING && VitaPerfNow() - start < timeoutUs)
		sceKernelDelayThread(1000);
	return fenceState;
}

// Frames waiting for the GPU (main thread -> poller) and completed frames
// (poller -> main thread): single producer, single consumer rings.
#define GPU_RING 64
struct PendingFrame {
	uint32_t frame, target;
	uint64_t submitUs, doneUs;	// doneUs != 0: already known (GPU sync mode)
};
struct DoneFrame {
	uint32_t frame;
	uint64_t doneUs;
};
static PendingFrame pending[GPU_RING];
static DoneFrame done[GPU_RING];
static std::atomic<uint32_t> pendingHead, pendingTail, doneHead, doneTail;
static std::atomic<bool> pollerSleeping;
static std::atomic<uint32_t> gpuQueueFull, gpuDoneFull, gpuTimeouts;
static uint32_t gpuQueueFullSeen, gpuDoneFullSeen, gpuTimeoutsSeen;
static SceUID pollerWake = -1, poller = -1;

static void
PushDone(uint32_t frame, uint64_t doneUs)
{
	uint32_t head = doneHead.load(std::memory_order_relaxed);
	if(head - doneTail.load(std::memory_order_acquire) >= GPU_RING){
		gpuDoneFull.fetch_add(1, std::memory_order_relaxed);
		return;
	}
	done[head % GPU_RING].frame = frame;
	done[head % GPU_RING].doneUs = doneUs;
	doneHead.store(head + 1, std::memory_order_release);
}

// Sleeps on a semaphore while nothing is pending, otherwise polls the
// notification every 150 us: completion times are within ~0.2 ms.
static int
GpuPoller(SceSize, void *)
{
	VitaPerfRegisterThread("BenchGpuFence");
	for(;;){
		uint32_t tail = pendingTail.load(std::memory_order_relaxed);
		if(tail == pendingHead.load()){
			pollerSleeping.store(true);
			if(tail == pendingHead.load()){
				SceUInt timeout = 100000;
				sceKernelWaitSema(pollerWake, 1, &timeout);
			}
			pollerSleeping.store(false);
			continue;
		}
		const PendingFrame &p = pending[tail % GPU_RING];
		uint64_t now = VitaPerfNow();
		if(p.doneUs || (int32_t)(*fenceAddress - p.target) >= 0){
			PushDone(p.frame, p.doneUs ? p.doneUs : now);
			pendingTail.store(tail + 1, std::memory_order_release);
		}else if(now - p.submitUs > 1000000){
			gpuTimeouts.fetch_add(1, std::memory_order_relaxed);
			pendingTail.store(tail + 1, std::memory_order_release);
		}else
			sceKernelDelayThread(150);
	}
	return 0;
}

static void
StartPoller(void)
{
	// Another user core than the main thread's, just above its priority so a
	// completion is seen promptly; each wake-up only costs a few microseconds.
	SceUID self = sceKernelGetThreadId();
	int mainMask = sceKernelGetThreadCpuAffinityMask(self);
	int mainPriority = sceKernelGetThreadCurrentPriority();
	SceKernelThreadInfo info;
	memset(&info, 0, sizeof(info));
	info.size = sizeof(info);
	int infoResult = sceKernelGetThreadInfo(self, &info);
	int mask = mainMask == SCE_KERNEL_CPU_MASK_USER_2 ? SCE_KERNEL_CPU_MASK_USER_1 : SCE_KERNEL_CPU_MASK_USER_2;
	int priority = mainPriority >= 64 + 8 && mainPriority <= 191 ? mainPriority - 8 : 0x10000100;
	pollerWake = sceKernelCreateSema("reLCS bench GPU wake", 0, 0, 1, nullptr);
	if(pollerWake >= 0)
		poller = sceKernelCreateThread("reLCS bench GPU fence", GpuPoller, priority, 16 * 1024, 0, mask, nullptr);
	if(poller >= 0 && sceKernelStartThread(poller, 0, nullptr) < 0){
		sceKernelDeleteThread(poller);
		poller = -1;
	}
	printf("[BENCH] main thread: mask=0x%X priority=%d cpu=%d (info rc=0x%X); GPU poller: mask=0x%X priority=0x%X %s\n",
	       (unsigned)mainMask, mainPriority, infoResult >= 0 ? info.currentCpuId : -1, (unsigned)infoResult,
	       (unsigned)mask, (unsigned)priority, poller >= 0 ? "started" : "FAILED");
}

// ---- Render experiments --------------------------------------------------------

static float viewportScale = 1.0f;
static bool scopeOpen, viewportChanged, gpuSync;
static uint32_t lastSyncUs;

// ---- Results files ---------------------------------------------------------------

static const char *
AbsolutePath(const char *path, char *buf, int size)
{
	if(strchr(path, ':'))
		return path;
	snprintf(buf, size, "%s%s", VITA_DATA_DIR, path);
	return buf;
}

static bool
WriteAll(SceUID fd, const void *data, uint32_t size)
{
	const char *p = (const char*)data;
	uint32_t written = 0;
	while(written < size){
		int n = sceIoWrite(fd, p + written, size - written);
		if(n <= 0)
			return false;
		written += (uint32_t)n;
	}
	return true;
}

// The result folder gets the benchmark log too (one [PERF] window per test):
// each results.json write appends what the log gained since the last copy.
static void
CopyLogNextTo(const char *path)
{
	static char lastDest[256];
	static SceOff copied;
	char dest[256];
	const char *slash = strrchr(path, '/');
	int dirLen = slash ? (int)(slash - path) + 1 : 0;
	if(snprintf(dest, sizeof(dest), "%.*slog.txt", dirLen, path) >= (int)sizeof(dest))
		return;
	if(!VitaLogWaitIdle(500000))
		printf("[BENCH] log copy: writer still busy\n");
	bool fresh = strcmp(dest, lastDest) != 0;
	SceUID in = sceIoOpen(BENCH_LOG, SCE_O_RDONLY, 0);
	if(in < 0){
		printf("[BENCH] log copy: cannot open %s (0x%08X)\n", BENCH_LOG, (unsigned)in);
		return;
	}
	SceOff size = sceIoLseek(in, 0, SCE_SEEK_END);
	SceOff from = fresh ? 0 : copied;
	if(size < from)
		from = 0, fresh = true;
	SceUID out = sceIoOpen(dest, SCE_O_WRONLY | SCE_O_CREAT | (fresh ? SCE_O_TRUNC : SCE_O_APPEND), 0666);
	if(out < 0){
		sceIoClose(in);
		return;
	}
	static char chunk[32 * 1024];
	sceIoLseek(in, from, SCE_SEEK_SET);
	bool ok = true;
	while(ok && from < size){
		SceOff left = size - from;
		int n = sceIoRead(in, chunk, left < (SceOff)sizeof(chunk) ? (SceSize)left : (SceSize)sizeof(chunk));
		if(n <= 0)
			break;
		ok = WriteAll(out, chunk, (uint32_t)n);
		from += n;
	}
	sceIoClose(out);
	sceIoClose(in);
	snprintf(lastDest, sizeof(lastDest), "%s", dest);
	copied = ok ? from : 0;
	if(!ok)
		lastDest[0] = '\0';	// rewrite it whole next time
}

namespace BenchPlatform {

void
Init(void)
{
	if(initialised)
		return;
	initialised = true;
	VitaSetFrameSampling(false);
	VitaGLProfSetCounting(true);
	ProbeCpuLoad();
	StartPoller();
	if(poller < 0)
		FenceFail("poller thread not started");
	printf("[BENCH] platform: build %s, GL counting forced, periodic heap sampling off\n", VITA_BUILD_ID);
	VitaFlushLog();
}

uint32_t
Caps(void)
{
	CheckCpuLoad(VitaPerfNow());	// settle the probe before the run freezes its caps
	uint32_t caps = BENCH_CAP_GPU_SYNC | BENCH_CAP_VIEWPORT | BENCH_CAP_DRAW_MODE | BENCH_CAP_FLAT_TEX |
		BENCH_CAP_SECTIONS | BENCH_CAP_GL_COUNTERS | BENCH_CAP_DISK | BENCH_CAP_THREADS | BENCH_CAP_ALLOC;
	// A linked notification symbol alone does not prove timing works on the
	// installed vitaGL build. Advertise it only after observing GPU progress.
	if(WaitFence(100000) == FENCE_OK)
		caps |= BENCH_CAP_GPU_FENCE;
	if(cpuLoadOk)
		caps |= BENCH_CAP_CPU_LOAD;
	return caps;
}

uint64_t NowUs(void) { return VitaPerfNow(); }

void
Tick(void)
{
	static uint64_t lastTick;
	uint64_t now = VitaPerfNow();
	if(lastTick && now - lastTick < 1000000)
		return;
	lastTick = now;
	// No input during a run: keep the console from dimming or suspending.
	sceKernelPowerTick(SCE_KERNEL_POWER_TICK_DEFAULT);
	sceKernelPowerTick(SCE_KERNEL_POWER_TICK_DISABLE_AUTO_SUSPEND);
	sceKernelPowerTick(SCE_KERNEL_POWER_TICK_DISABLE_OLED_DIMMING);
	CheckCpuLoad(now);
}

const char *ResultsRoot(void) { return VITA_DATA_DIR "benchmark/"; }

void
Timestamp(char *buf, int size)
{
	SceDateTime t;
	memset(&t, 0, sizeof(t));
	sceRtcGetCurrentClockLocalTime(&t);
	snprintf(buf, size, "%04u-%02u-%02u_%02u-%02u-%02u", t.year, t.month, t.day, t.hour, t.minute, t.second);
}

bool
MakeDir(const char *path)
{
	char abs[256], dir[256];
	int len = snprintf(dir, sizeof(dir), "%s", AbsolutePath(path, abs, sizeof(abs)));
	if(len <= 0 || len >= (int)sizeof(dir))
		return false;
	while(len > 0 && dir[len - 1] == '/')
		dir[--len] = '\0';
	int rc = sceIoMkdir(dir, 0777);
	if(rc >= 0 || (unsigned)rc == ERRNO_EEXIST)
		return true;
	SceIoStat st;
	if(sceIoGetstat(dir, &st) >= 0 && SCE_S_ISDIR(st.st_mode))
		return true;
	printf("[BENCH] mkdir %s failed: 0x%08X\n", dir, (unsigned)rc);
	return false;
}

bool
WriteFile(const char *path, const void *data, uint32_t size)
{
	char abs[256];
	path = AbsolutePath(path, abs, sizeof(abs));
	SceUID fd = sceIoOpen(path, SCE_O_WRONLY | SCE_O_CREAT | SCE_O_TRUNC, 0666);
	if(fd < 0){
		printf("[BENCH] cannot create %s: 0x%08X\n", path, (unsigned)fd);
		return false;
	}
	bool ok = WriteAll(fd, data, size);
	ok = sceIoClose(fd) >= 0 && ok;
	if(!ok)
		printf("[BENCH] write %s failed (%u bytes)\n", path, size);
	else{
		const char *name = strrchr(path, '/');
		// results.json after each test, summary.txt last in WriteResults
		const char *base = name ? name + 1 : path;
		if(strcmp(base, "results.json") == 0 || strcmp(base, "summary.txt") == 0)
			CopyLogNextTo(path);
	}
	return ok;
}

int
ReadSettingsFile(char *buf, int size)
{
	if(size <= 0)
		return -1;
	buf[0] = '\0';
	SceUID fd = sceIoOpen(VITA_DATA_DIR "benchmark.ini", SCE_O_RDONLY, 0);
	if(fd < 0)
		return -1;
	int total = 0;
	while(total < size - 1){
		int n = sceIoRead(fd, buf + total, size - 1 - total);
		if(n <= 0)
			break;
		total += n;
	}
	sceIoClose(fd);
	buf[total] = '\0';
	return total;
}

void
DeviceInfo(BenchDeviceInfo *out)
{
	memset(out, 0, sizeof(*out));
	bool tv = sceKernelIsPSVitaTV() != 0;
	snprintf(out->platform, sizeof(out->platform), "%s", tv ? "PS TV" : "PS Vita");
	snprintf(out->model, sizeof(out->model), "%s (0x%X)", tv ? "PS TV" : "PS Vita", (unsigned)sceKernelGetModel());
	SceKernelSystemSwVersion version;
	memset(&version, 0, sizeof(version));
	version.size = sizeof(version);
	if(sceKernelGetSystemSwVersion(&version) >= 0)
		snprintf(out->firmware, sizeof(out->firmware), "%.15s", version.versionString);
	else
		snprintf(out->firmware, sizeof(out->firmware), "unknown");
	snprintf(out->build, sizeof(out->build), "%s", VITA_BUILD_ID);
	out->cpuMHz = scePowerGetArmClockFrequency();
	out->busMHz = scePowerGetBusClockFrequency();
	out->gpuMHz = scePowerGetGpuClockFrequency();
	out->xbarMHz = scePowerGetGpuXbarClockFrequency();
	snprintf(out->gpu, sizeof(out->gpu), "SGX543MP4+ (vitaGL)");
	out->screenW = SCREEN_W;
	out->screenH = SCREEN_H;
	snprintf(out->notes, sizeof(out->notes), "fence=%s; %s", fenceWhy, cpuNote);
}

uint32_t
RawButtons(void)
{
	// Same call as the game's pad (glfw_vita.cpp): also reads a PS TV DualShock.
	SceCtrlData ctrl;
	memset(&ctrl, 0, sizeof(ctrl));
	if(sceCtrlPeekBufferPositiveExt2(0, &ctrl, 1) < 0)
		return 0;
	unsigned int b = ctrl.buttons;
	uint32_t out = 0;
	if(b & SCE_CTRL_CROSS) out |= BENCH_BTN_CROSS;
	if(b & SCE_CTRL_CIRCLE) out |= BENCH_BTN_CIRCLE;
	if(b & SCE_CTRL_START) out |= BENCH_BTN_START;
	if(b & SCE_CTRL_SELECT) out |= BENCH_BTN_SELECT;
	if(b & SCE_CTRL_TRIANGLE) out |= BENCH_BTN_TRIANGLE;
	if(b & SCE_CTRL_UP) out |= BENCH_BTN_UP;
	if(b & SCE_CTRL_DOWN) out |= BENCH_BTN_DOWN;
	return out;
}

void
ReadCounters(BenchCounters *out)
{
	VitaGLTotals gl;
	VitaGLGetTotals(&gl);
	VitaPerfTotals perf;
	VitaPerfGetTotals(&perf);
	memset(out, 0, sizeof(*out));
	out->draws = gl.draws;
	out->indices = gl.indices;
	out->uniforms = gl.uniforms;
	out->texBinds = gl.texBinds;
	out->bufBinds = gl.bufBinds;
	out->programs = gl.programs;
	out->stateCalls = gl.stateCalls;
	out->vertexUploadBytes = gl.vertexBytes;
	out->indexUploadBytes = gl.indexBytes;
	out->textureUploadBytes = gl.textureBytes;
	out->textureUploadUs = gl.textureUs;
	out->shaderCompiles = gl.shaderCompiles;
	out->diskReads = perf.diskReads;
	out->diskBytes = perf.diskBytes;
	out->diskReadUs = perf.diskUs;
	out->diskSyncWaits = perf.syncWaits;
	out->diskSyncUs = perf.syncUs;
	out->allocCalls = perf.allocCalls;
	out->freeCalls = perf.freeCalls;
	out->allocBytes = perf.allocBytes;
}

void
ReadMemory(BenchMemory *out)
{
	memset(out, 0, sizeof(*out));
	const struct mallinfo mi = mallinfo();
	out->heapUsed = mi.uordblks;
	out->heapTotal = _newlib_heap_size_user;
	if(!GLReady())
		return;	// vitaGL pools exist once vglInit has run
	out->gpuRamFree = vglMemFree(VGL_MEM_RAM);
	out->gpuRamTotal = vglMemTotal(VGL_MEM_RAM);
	out->cdramFree = vglMemFree(VGL_MEM_VRAM);
	out->cdramTotal = vglMemTotal(VGL_MEM_VRAM);
	out->phycontFree = vglMemFree(VGL_MEM_PHYCONT);
	out->phycontTotal = vglMemTotal(VGL_MEM_PHYCONT);
}

static void
AddThread(BenchThreadTimes *out, const char *name, uint64_t runUs)
{
	if(out->count >= BENCH_MAX_THREADS)
		return;
	snprintf(out->name[out->count], sizeof(out->name[0]), "%s", name);
	out->runUs[out->count] = runUs;
	out->count++;
}

void
ReadThreadTimes(BenchThreadTimes *out)
{
	memset(out, 0, sizeof(*out));
	int n = VitaPerfThreadCount();
	for(int i = 0; i < n; i++){
		const char *name;
		uint64_t run;
		if(VitaPerfThreadRunTime(i, &name, &run))
			AddThread(out, name, run);
	}
	// vitaGL's garbage collector (resource frees, handshake in vglSwapBuffers)
	static int gcState;	// 0 untested, 1 ok, -1 unavailable
	if(gcState < 0 || !GLReady() || gc_thread <= 0)
		return;
	SceKernelThreadInfo info;
	memset(&info, 0, sizeof(info));
	info.size = sizeof(info);
	int rc = sceKernelGetThreadInfo(gc_thread, &info);
	if(gcState == 0){
		gcState = rc >= 0 ? 1 : -1;
		printf("[BENCH] vitaGL GC thread 0x%X: %s (rc=0x%X)\n", (unsigned)gc_thread,
		       rc >= 0 ? "readable" : "unavailable", (unsigned)rc);
	}
	if(rc >= 0)
		AddThread(out, "vitaGL GC", info.runClocks);
}

void
ReadCpuLoad(BenchCpuLoad *out)
{
	memset(out, 0, sizeof(*out));
	if(!cpuLoadOk)
		return;
	SceKernelSystemInfo info;
	if(ReadSystemInfo(&info) < 0)
		return;
	out->wallUs = VitaPerfNow();
	// Core 3 belongs to the system; report the valid cores from core 0 up.
	for(int i = 0; i < 4 && CoreValid(info, i); i++){
		out->idleUs[i] = info.cpuInfo[i].idleClock;
		out->cores = i + 1;
	}
}

void
FrameSubmitted(uint32_t frame)
{
	// A frame that skipped End3D must not carry its experiments into the next one.
	if(scopeOpen)
		End3D();
	uint64_t knownDone = 0;
	lastSyncUs = 0;
	if(gpuSync && GLReady()){
		// No scene is open right after vglSwapBuffers (BeginScene is deferred to
		// the next draw), so this only waits; glFinish would restart a scene.
		uint64_t start = VitaPerfNow();
		sceGxmFinish(gxm_context);
		knownDone = VitaPerfNow();
		uint64_t wait = knownDone - start;
		lastSyncUs = wait > 0xFFFFFFFFu ? 0xFFFFFFFFu : (uint32_t)wait;
	}
	if(CheckFence() != FENCE_OK)
		return;
	uint32_t target = query_fence.value;
	if(target == lastTarget)
		return;		// nothing new reached the GPU in this frame
	lastTarget = target;
	uint32_t head = pendingHead.load(std::memory_order_relaxed);
	if(head - pendingTail.load(std::memory_order_acquire) >= GPU_RING){
		gpuQueueFull.fetch_add(1, std::memory_order_relaxed);
		return;
	}
	PendingFrame &p = pending[head % GPU_RING];
	p.frame = frame;
	p.target = target;
	p.submitUs = VitaPerfNow();
	p.doneUs = knownDone;
	pendingHead.store(head + 1);
	if(pollerSleeping.load())
		sceKernelSignalSema(pollerWake, 1);
}

bool
PollGpuDone(uint32_t *frame, uint64_t *doneUs)
{
	uint32_t tail = doneTail.load(std::memory_order_relaxed);
	if(tail == doneHead.load(std::memory_order_acquire))
		return false;
	*frame = done[tail % GPU_RING].frame;
	*doneUs = done[tail % GPU_RING].doneUs;
	doneTail.store(tail + 1, std::memory_order_release);
	return true;
}

void SetGpuSync(bool on) { gpuSync = on; }
uint32_t LastGpuSyncWaitUs(void) { return lastSyncUs; }

bool
SetViewportScale(float scale)
{
	viewportScale = scale >= 1.0f ? 1.0f : scale > 0.0f ? scale : 0.0f;
	return true;
}

bool
SetDrawMode(int mode)
{
	if(mode < BENCH_DRAW_NORMAL || mode > BENCH_DRAW_NULL)
		return false;
	VitaGLBenchSetDrawMode(mode);
	return true;
}

bool
SetFlatTextures(bool on)
{
	VitaGLBenchSetFlatTextures(on);
	return true;
}

void
Begin3D(void)
{
	if(scopeOpen)
		return;
	scopeOpen = true;
	VitaGLBenchScope3D(true);
	if(viewportScale < 1.0f && GLReady()){
		// vitaGL: bottom-left corner of the display, applied immediately
		int w = (int)(SCREEN_W * viewportScale + 0.5f);
		int h = (int)(SCREEN_H * viewportScale + 0.5f);
		glViewport(0, 0, w < 1 ? 1 : w, h < 1 ? 1 : h);
		viewportChanged = true;
	}
}

void
End3D(void)
{
	if(!scopeOpen)
		return;
	scopeOpen = false;
	VitaGLBenchScope3D(false);
	if(viewportChanged){
		// librw caches the full-screen viewport: make it true again.
		glViewport(0, 0, SCREEN_W, SCREEN_H);
		viewportChanged = false;
	}
}

int SectionCount(void) { return VitaProfSectionCount(); }
const char *SectionName(int i) { return VitaProfSectionName(i); }
int SectionParent(int i) { return VitaProfSectionParent(i); }
int SectionDepth(int i) { return VitaProfSectionDepth(i); }
uint32_t SectionFrameUs(int i) { return VitaProfSectionFrameUs(i); }
uint32_t SectionFrameCalls(int i) { return VitaProfSectionFrameCalls(i); }

void SetPeriodicReports(bool on) { VitaPerfSetPeriodicReports(on); }
void LogWindowBegin(void) { VitaPerfSceneWindowBegin(); }

void
LogWindowEnd(const char *scene)
{
	VitaPerfSceneWindowEnd(scene);
	uint32_t full = gpuQueueFull.load(), doneFull = gpuDoneFull.load(), timeouts = gpuTimeouts.load();
	if(full != gpuQueueFullSeen || doneFull != gpuDoneFullSeen || timeouts != gpuTimeoutsSeen)
		printf("[BENCH] GPU fence losses: queue_full=%u done_full=%u timeouts=%u (cumulative)\n",
		       full, doneFull, timeouts);
	gpuQueueFullSeen = full;
	gpuDoneFullSeen = doneFull;
	gpuTimeoutsSeen = timeouts;
}

void FlushLog(void) { VitaFlushLog(); }

} // namespace BenchPlatform

#endif
